import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./components/cart-provider";
import { ProductsProvider } from "./components/products-provider";
import SiteHeader from "./components/site-header";
import SupportChat from "./components/support-chat";
import { getProducts } from "@/lib/products";
import { getSessionFromCookies } from "@/lib/auth";
import { getUserById } from "@/lib/users";
import { getCartItemsForUser } from "@/lib/cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialProducts = await getProducts();
  const session = await getSessionFromCookies();
  const currentUser = session ? await getUserById(session.userId) : null;
  const initialCartItems = currentUser
    ? await getCartItemsForUser(currentUser.id)
    : [];
  const cartProviderKey = `${currentUser?.id ?? "guest"}:${initialCartItems
    .map((item) => `${item.id}:${item.cantidad}`)
    .join("|")}`;

  return (
    <html lang="es" className="h-full antialiased" data-scroll-behavior="smooth">
      <body className="min-h-full flex flex-col">
        <ProductsProvider initialProducts={initialProducts}>
          <CartProvider
            key={cartProviderKey}
            initialItems={initialCartItems}
            currentUserId={currentUser?.id ?? null}
          >
            <SiteHeader
              currentUser={
                currentUser
                  ? { fullName: currentUser.fullName, role: currentUser.role }
                  : null
              }
            />
            {children}
            <SupportChat />
          </CartProvider>
        </ProductsProvider>
      </body>
    </html>
  );
}
